# https://git-cliff.org/docs/configuration

[changelog]

body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group | striptags | trim }}

{% for commit in commits -%}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endfor -%}

{% endfor %}
"""

trim = true

[bump]
initial_tag = "0.1.0"
breaking_always_bump_major = false

[git]
conventional_commits = true
filter_unconventional = true
tag_pattern = "^[0-9]+\\.[0-9]+\\.[0-9]+$"

commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->New Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", group = "<!-- 3 -->Refactoring" },
  { message = "^docs", group = "<!-- 4 -->Documentation" },
  { message = "^(build|ci|test|chore)", skip = true },
  { message = ".*", group = "<!-- 5 -->Other Changes" },
]

sort_commits = "oldest"
topo_order = false
